name: Friday PM

on:
  workflow_dispatch:
  schedule:
    - cron: "1 10 * * 5"

jobs:
  Back: 
   runs-on: ubuntu-latest
   steps:
    - name: what's the time
      run: date
    - run: |
        echo "WebGL2 3D Perspective"
        sleep 5
        echo "WebGL2 3D Perspective"
        sleep 5
        echo "WebGL2 3D Perspective"
        sleep 5
        echo "Perspective"