name: Monday PM

on:
  workflow_dispatch:
  schedule:
    - cron: "1 10 * * 1"

jobs:
  Back: 
   runs-on: ubuntu-latest
   steps:
    - name: what's the time
      run: date
    - name: Perspective
      run: echo "To activate 3D space, an element needs perspective. This can be applied in two ways using the transform property, with the perspective as a functional notation."
    - name: The Core Perspective Algorithm
      run: |
          echo " (What the GPU really does)"
          echo "OpenGL-style perspective projection matrix."
    - name: The Perspective Projection Matrix
      run: |
          echo "mat4.perspective(out, fovY, aspect, near, far)"
          echo "f/aspect 0 0 0"
          echo "0 f 0 0"
          echo "..."
    - name: The Four Spaces a Vertex Travels Through
      run: |
          echo "View / Eye / Camera | (x,y,z) relative to camera 	 | View matrix (inverse of camera transform)"