name: Monday PM

on:
  workflow_dispatch:
  schedule:
    - cron: "1 10 * * 1"

jobs:
  Back: 
   runs-on: ubuntu-latest
   steps:
    - name: what's the time
      run: date
    - name: Back to Webgl
      run: echo "webgl 3D"
    - name: Why
      run: |
          echo "I don't known why."