name: Monday PM

on:
  workflow_dispatch:
  schedule:
    - cron: "1 10 * * 1"

jobs:
  Back: 
   runs-on: ubuntu-latest
   steps:
    - name: what's the time
      run: date
    - name: 3D Perspective Algorithms 
      run: echo "exactly what actually happens inside the GPU when you call mat4.perspective() and why it creates that realistic 'far = smaller' effect."
    - name: The Core Perspective Algorithm
      run: |
          echo " (What the GPU really does)"
          echo "OpenGL-style perspective projection matrix."