name: Saturday AM

on:
  workflow_dispatch:
  schedule:
    - cron: "1 0 * * 6"

jobs:
  Push: 
   runs-on: ubuntu-latest
   steps:
    - name: what's the time
      run: date
    - name: The Four Spaces a Vertex Travels Through
      run: |
        echo "step: Object/Model"
        echo "step: World"
        echo "step: View / Eye / Camera"
        echo "step: Clip"
        echo "step: NDC (Normalized Device)"
        echo "step: Screen "