name: Sunday AM

on:
  workflow_dispatch:
  schedule:
    - cron: "1 0 * * 0"

jobs:
  Push: 
   runs-on: ubuntu-latest
   steps:
    - name: what's the time
      run: date
    - name: mat4.perspective out, fov, aspect, near, far
      run: |
          echo "far | number | Distance to the far clipping plane (must be > near)"
