name: Thursday AM

on:
  workflow_dispatch:
  schedule:
    - cron: "1 0 * * 4"

jobs:
  Push: 
   runs-on: ubuntu-latest
   steps:
    - name: what's the time
      run: date
    - name: What is a 3D perspective ?
      run: |
          echo "A perspective allows you to see in three dimensions, width, depth and height. The name 3D perspective would be a pleonasm, because the perspective is in itself a three-dimensional representation. It can be used in an interior or exterior architectural project."
          echo "The 3D visualization  can be different according to the needs, but in any case it brings an undeniable added value during presentations for competitions, building permits, sales brochures, for example."
    - name: mat4.perspective(out, fov, aspect, near, far)
      run: |
          echo "aspect | Number | Aspect ratio = canvas width รท canvas height (e.g. 16/9, 4/3, 1, etc.)"