name: Tuesday PM

on:
  workflow_dispatch:
  schedule:
    - cron: "1 10 * * 2"

jobs:
  Back: 
   runs-on: ubuntu-latest
   steps:
    - name: what's the time
      run: date
    - name: WebGL2 3D Perspective
      run: |
          echo "Why is the fact that WebGL automatically divides by W useful? Because now, using more matrix magic, we can just use yet another matrix to copy z to w."