name: Tuesday PM

on:
  workflow_dispatch:
  schedule:
    - cron: "1 10 * * 2"

jobs:
  Back: 
   runs-on: ubuntu-latest
   steps:
    - name: what's the time
      run: date
    - name: mat4.perspective(out, fov, aspect, near, far)
      run: |
          echo "out : mat4 : The receiving matrix (will be overwritten with the result)"
    - name: mat4.perspective out,fov
      run: |
          echo "fovy : number : Field of view in radians in the vertical direction (y-axis)"