name: Wednesday PM

on:
  workflow_dispatch:
  schedule:
    - cron: "1 10 * * 3"

jobs:
  Back: 
   runs-on: ubuntu-latest
   steps:
    - name: what's the time
      run: date
    - name: Perspective Projection Matrix
      run: |
          echo "line1: 2n/r-1 0 r+l/r-l 0"