name: Wednesday AM

on:
  workflow_dispatch:
  schedule:
    - cron: "1 0 * * 3"

jobs:
  Push: 
   runs-on: ubuntu-latest
   steps:
    - name: what's the time
      run: date
    - name: Further Mathematics
      run: echo "Matrices and transformations"
    - name: Transformations
      run: |
          echo "The original point, or shape, is called the object."
          echo "The new point, or shape, after the transformation, is called the image."
          echo "A transformation is a mapping of an object onto its image"
          echo "Reflection  Rotation  Enlargement "
    - name: mat4.perspective out,fov,aspect
      run: |
          echo "aspect | Number | Aspect ratio = canvas width รท canvas height (e.g. 16/9, 4/3, 1, etc.)"